### ISSUE TITLE
Check if it's a mcat widget url

### ISSUE THREAD

**Issue by jonasnp5** [RedCrafter07/mcat-discord-rpc#1]
If i log in with a random url like https://d.com/ i come into the dashboard. 

It think the easy way is check if it's a mcat widget url.

**Comment by RedCrafter07** [comment]
Thank you :)

**Comment by RedCrafter07** [comment]
This will be fixed in the next version, the commit for that is available already. Thanks for the bug report!

**Comment by RedCrafter07** [comment]
Fixed in version 1.0.5
